// app/head.tsx
export default function Head() {
    return (
      <>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <title>Coin X Gamification | 2025</title>
        <meta name="description" content="Generated by create next app" />
      </>
    );
  }
  